//...
try
{
	//...
}
catch(<exceção1> <nome1>)
{
	//...
}
//...
catch(esxceçãoN> <nomeN>)
{
	//...
}
//...